//task 1 Что не так в нижеприведённом тесте функции pow
//в одном тесте объеденины три теста
//если крашнется один внутри, придется выяснять с какими данными он крашнулся
// it("Возводит x в степень n", function() {
//     let x = 5;
//
//     let result = x;
//     assert.equal(pow(x, 1), result);
//
//     result *= x;
//     assert.equal(pow(x, 2), result);
//
//     result *= x;
//     assert.equal(pow(x, 3), result);
// });